APP-5717: [Android] Show correlation_id on screen in case of 5xx status code
paysera/kotlin-lib-common-sdk pull request #28
Opened 2023-08-14 10:58 UTC by s-k-georgiev

2023-08-14 11:00 UTC, s-k-georgiev commented
@gilbertparreno Do we need to also update `RefreshingCoroutineCallAdapterFactory`, or it is used for refreshing tokens, and thus will not be used in showing 5xx errors?

2023-08-17 02:37 UTC, gilbertparreno commented
We should also handle this error in `RefreshingCoroutineCallAdapterFactory.makeRequest(request: CallAdapterRequest)`

2023-09-14 07:47 UTC, eunicegalang requested changes

2023-09-14 07:55 UTC, gilbertparreno commented on buildSrc/src/main/kotlin/ApplicationConfiguration.kt
> +    const val version = "2.6.12"
its already **.10**.

2023-09-14 09:48 UTC, eunicegalang approved these changes

2023-09-15 00:51 UTC, merged